# Generated by Django 4.0.8 on 2023-01-20 09:48

import api.utills.constraints
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'NOT_STARTED'), ('on_going', 'ON_GOING'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], default=api.utills.constraints.TransactionStatus['NOT_STARTED'], max_length=20)),
                ('refree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.participant')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.participant')),
            ],
        ),
    ]
