# Generated by Django 4.0.8 on 2023-01-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0005_eventusermap'),
        ('authentication', '0002_remove_user_role_userrolemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_game_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventgamemap')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_game_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventgamemap')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('user_role_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap')),
            ],
        ),
    ]
