# Generated by Django 4.0.8 on 2023-01-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('team', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_role_map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap'),
        ),
    ]
