# Generated by Django 4.0.8 on 2023-01-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('team', '0003_alter_participant_team_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_role_map_id',
            field=models.ForeignKey(limit_choices_to={'role_id': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap'),
        ),
    ]
