# Generated by Django 4.0.8 on 2023-01-20 06:13

import api.utills.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[], default=api.utills.constraints.TransactionStatus['NOT_STARTED'], max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('max_players', models.IntegerField()),
                ('min_players', models.IntegerField()),
            ],
        ),
    ]
