# Generated by Django 4.0.8 on 2023-01-20 06:14

import api.utills.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('not_started', 'NOT_STARTED'), ('on_going', 'ON_GOING'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], default=api.utills.constraints.TransactionStatus['NOT_STARTED'], max_length=20),
        ),
    ]
