# Generated by Django 4.0.8 on 2023-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_players',
            field=models.IntegerField(default=0),
        ),
    ]
