# Generated by Django 4.0.8 on 2023-01-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('event', '0004_eventgamemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap')),
            ],
        ),
    ]
