# Generated by Django 4.0.8 on 2023-01-24 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('event', '0006_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventusermap',
            name='user_id',
            field=models.ForeignKey(limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap'),
        ),
    ]
