# Generated by Django 4.0.8 on 2023-02-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role_userrolemap'),
        ('event', '0007_alter_eventusermap_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventusermap',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userrolemap'),
        ),
    ]
