# Generated by Django 4.0.8 on 2023-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TimeField(max_length=300)),
                ('no_of_players', models.IntegerField(default=0)),
                ('is_indoor', models.BooleanField(default=True)),
                ('is_team_game', models.BooleanField(default=True)),
            ],
        ),
    ]
